export const SEARCH_USER = 'SEARCH_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_REPOS = 'ADD_REPOS';
export const ADD_REPOS_FAILURE = 'ADD_REPOS_FAILURE';
export const ADD_COMMITS = 'ADD_COMMITS';
export const ADD_COMMITS_FAILURE = 'ADD_COMMITS_FAILURE';
